虽然绝大多数时间都是使用列表，但是Python中提供了多样的数据结构，比如适合存放浮点数的数组array、适合频繁先进先出操作的双端队列deque、需要频繁判断元素是否存在的集合set。
使用memoryview可以对同一块内存进行不同的解释，类似于C的类型转换。

### 2.9.1 数组

In [1]:
# 一个浮点型数组的创建、存入文件和从文件读取的过程

from array import array
from random import random

In [2]:
# 返回一个包含10^7个随机数的double类型的数组
floats = array('d', (random() for i in range(10**7)))

In [4]:
floats[-1]

0.8576969271767513

In [5]:
# 保存
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [6]:
# 读取
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

In [7]:
floats2[-1]

0.8576969271767513

In [9]:
print(floats2 == floats)
id(floats), id(floats2)

True


(2179007921776, 2179006885104)

### 2.9.2 内存视图

In [14]:
# 创建short类型数组
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [15]:
memv[0]

-2

In [16]:
# 转换为无符号字符，原来的5个元素变成了10个
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [17]:
# Hex:00000000 -> Hex:00004000_h = Bin:0100 0000 0000 0000 = 2^10 = 1024
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

### 2.9.3 NumPy和SciPy

In [18]:
import numpy

a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
type(a)

numpy.ndarray

In [21]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a[2]

array([ 8,  9, 10, 11])

In [23]:
a[2, 1]

9

In [25]:
a[:, 1]

array([1, 5, 9])

In [26]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
floats = numpy.loadtxt('floats-10M-lines.txt')

floats[-3:]
floats *= .5
floats[-3:]

In [ ]:
from time import perf_counter as pc

t0 = pc(); floats /= 3; pc() - t0

numpy.save('floats-10M', floats)

floats2 = numpy.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]

### 2.9.4 双向队列和其他形式的队列

In [28]:
from collections import deque

In [37]:
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [38]:
# 当n > 0时，队列的最右边的n个元素会被移动到队列的左边。当n < 0时，最左边的n个元素会被移动到右边。
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [39]:
dq.rotate(-3)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [40]:
dq.appendleft(-1)
dq

deque([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8], maxlen=10)

In [41]:
dq.extend([22, 222, 2222])
dq

deque([2, 3, 4, 5, 6, 7, 8, 22, 222, 2222], maxlen=10)

In [42]:
dq.extendleft([55, 555, 555])
dq

deque([555, 555, 55, 2, 3, 4, 5, 6, 7, 8], maxlen=10)